---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  entrypoint.sh: |-
    #!/bin/bash
    apt update && apt -o Apt::Get::Assume-Yes=true install git curl bash unzip vim
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    nvm install 18
    cd /root
    git clone https://github.com/BernhardRode/dynamoose-tester.git
    cd dynamoose-tester
    npm i
    echo "run source ~/.bashrc && cd /root/dynamoose-tester && npm start"

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  serviceAccountName: ddb-serviceaccount
  containers:
    - name: ubuntu
      image: ubuntu:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - name: configmap-volume
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
      env:
        - name: ENABLE_IRP
          value: "true"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
  volumes:
    - name: configmap-volume
      configMap:
        defaultMode: 0700
        name: my-configmap
